name: Hello world!
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to say hello to'
        required: true
      mood:
        description: 'How to say hello'
        required: true
        type: choice
        options:
          - happy
          - grumpy
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello!
        run: |
          if [[ "${{ inputs.mood }}" == "happy" ]]; then
            face="8o) !"
          else
            face=">8o( ..."
          fi
          echo "Hello ${{ inputs.name }} ${face}"
  take-a-look:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: demo
      - name: Whats this?
        run: cat demo.txt
  take-a-second-look:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: demo
      - name: Whats this?
        id: look
        run: |
          echo "content=$(cat demo.txt)" >> $GITHUB_OUTPUT
          echo "ACTION='we looked'" >> $GITHUB_ENV
      - name: Check the output
        run: |
          echo "what did we do? ${{ env.ACTION }}"
          echo "The content is '${{ steps.look.outputs.content }}'"

